// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LndTypes.proto

#include "LndTypes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace lndtypes {
}  // namespace lndtypes
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_LndTypes_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_LndTypes_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_LndTypes_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_LndTypes_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_LndTypes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016LndTypes.proto\022\010lndtypes*\260\001\n\026Lightning"
  "PaymentReason\022\032\n\026UNKNOWN_PAYMENT_REASON\020"
  "\000\022\023\n\017PAYMENT_PAYMENT\020\001\022\030\n\024PAYMENT_SWAP_P"
  "AYMENT\020\002\022\022\n\016PAYMENT_RENTAL\020\003\022\034\n\030PAYMENT_"
  "RENTAL_EXTENSION\020\004\022\031\n\025PAYMENT_ORDERBOOK_"
  "FEE\020\005*z\n\025LightingInvoiceReason\022\032\n\026UNKNOW"
  "N_INVOICE_REASON\020\000\022\023\n\017INVOICE_PAYMENT\020\001\022"
  "\030\n\024INVOICE_SWAP_PAYMENT\020\002\022\026\n\022INVOICE_REF"
  "UND_FEE\020\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_LndTypes_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_LndTypes_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_LndTypes_2eproto_once;
static bool descriptor_table_LndTypes_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_LndTypes_2eproto = {
  &descriptor_table_LndTypes_2eproto_initialized, descriptor_table_protodef_LndTypes_2eproto, "LndTypes.proto", 337,
  &descriptor_table_LndTypes_2eproto_once, descriptor_table_LndTypes_2eproto_sccs, descriptor_table_LndTypes_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_LndTypes_2eproto::offsets,
  file_level_metadata_LndTypes_2eproto, 0, file_level_enum_descriptors_LndTypes_2eproto, file_level_service_descriptors_LndTypes_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_LndTypes_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_LndTypes_2eproto), true);
namespace lndtypes {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LightningPaymentReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_LndTypes_2eproto);
  return file_level_enum_descriptors_LndTypes_2eproto[0];
}
bool LightningPaymentReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LightingInvoiceReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_LndTypes_2eproto);
  return file_level_enum_descriptors_LndTypes_2eproto[1];
}
bool LightingInvoiceReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace lndtypes
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
