name: Build linux

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Push events on master branch
    # branches-ignore:
    #  - '**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: yuraolex/useful:cpp-connan-ubuntu-18
    env:
      working-directory: sources

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.working-directory}}

      - name: Prepare conan
        run: conan config set general.revisions_enabled=1 && conan remote add jfrog-x9developers https://stakenetwallet.jfrog.io/artifactory/api/conan/light-wallet-conan && conan user
      - name: Download packages
        run: mkdir -p build && cd build && conan install ../src -s compiler.libcxx=libstdc++11
        working-directory: ${{env.working-directory}}
      - name: Build project
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../src \
            && cmake --build . --target Stakenet lssd --parallel 2
        working-directory: ${{env.working-directory}}/build

      - name: Install project
        run: |
          LD_LIBRARY_PATH=$PWD/lib cmake --install . --component lssd \
            && LD_LIBRARY_PATH=$PWD/lib cmake --install . --component Stakenet
        working-directory: ${{env.working-directory}}/build

      - name: Install tools
        run: ./install-tools.sh
        working-directory: ${{env.working-directory}}/deploy

      - name: Prepare env for lssd deployment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          export TMP_LSSD_TAG=$(grep CMAKE_PROJECT_VERSION:STATIC CMakeCache.txt | cut -d "=" -f2 | tr -d '\n')
          echo "::set-env name=LSSD_TAG::$TMP_LSSD_TAG"
        working-directory: ${{env.working-directory}}/build

      - name: Publish lssd
        uses: tix-factory/release-manager@v1
        with:
          mode: uploadReleaseAsset
          filePath: ${{env.working-directory}}/build/package/lssd.zip
          assetName: lssd.zip
          tag: ${{env.LSSD_TAG}}
          repo: stakenet-light-wallet
          owner: X9Developers

      - name: Prepare lnd tar
        run: tar -czvf lnd.tar.gz lnd_*
        working-directory: ${{env.working-directory}}/build/bin

      - name: Deploy to staging
	env:
          AWS_ACCESS_KEY_ID: secrets.AWS_ACCESS_KEY_ID
	  AWS_SECRET_ACCESS_KEY: secrets.AWS_SECRET_ACCESS_KEY
        run: AWS_EC2_METADATA_DISABLED=true cmake -DDEPLOY_ENV="production" -DPLATFORM="linux" -DINSTALLER=$PWD/package/Stakenet.zip -DUPDATE_DIR=$PWD/package/update/$GITHUB_SHA -P $PWD/../cmake/s3-deploy-update.cmake
        working-directory: ${{env.working-directory}}/build

      - name: Publish lnd tar
        uses: tix-factory/release-manager@v1
        with:
          mode: uploadReleaseAsset
          filePath: ${{env.working-directory}}/build/bin/lnd.tar.gz
          assetName: lnd.tar.gz
          tag: ${{env.LSSD_TAG}}
          repo: stakenet-light-wallet
          owner: X9Developers

      - uses: "Ilshidur/action-discord@0.3.0"
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/747792295692337223/RkigsTZtTOeqVUt2QeS2sLlxsMg6OQBm8DsDseu8AoZob7grDa3xcbF8IjW8jyEv26Q6
        with:
          args: "Linux version ready: ${{env.LSSD_TAG}}"
